version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
    reviewers:
      - akhdrv
    commit-message:
      prefix: ci
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
    reviewers:
      - akhdrv
    commit-message:
      prefix: build
    ignore:
      - dependency-name: react
        versions: [ ">=19" ]
      - dependency-name: react-dom
        versions: [ ">=19" ]
    open-pull-requests-limit: 10
    versioning-strategy: increase
