name: Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Unit testing
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Setup packages
        run: pnpm install

      - name: Unit tests
        run: npx lerna run test

  lint:
    name: Linting
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Setup packages
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Type Check
        run: npx lerna run typecheck

  integration:
    strategy:
      matrix:
        node: [ 16, 18 ]
        react: [ 16, 17, 18 ]
    name: Integration testing (Node ${{ matrix.node }}, React ${{ matrix.react }})
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: Setup packages
        run: pnpm install

      - name: Run tests
        env:
          REACT_VERSION: ${{ matrix.react }}
        run: |
          cd spec/main-suite
          npm run integration:prepare
          npm run integration:all
          npm run integration:check
