name: Integration testing

on:
  merge_group:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  basic:
    strategy:
      matrix:
        node: [ 16, 18 ]
        react: [ 16, 17, 18 ]
    name: Basic (Node ${{ matrix.node }}, React ${{ matrix.react }})
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: Setup packages
        run: pnpm install

      - name: Run tests
        env:
          REACT_VERSION: ${{ matrix.react }}
        run: |
          cd spec/main-suite
          npm run integration:prepare
          npm run integration:all
          npm run integration:check

  npm:
    name: Project using NPM
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Setup packages
        run: pnpm install

      - name: Prepare
        run: |
          cd spec/main-suite
          npm run integration:prepare

      - name: Install via NPM
        run: |
          cd spec/main-suite
          rm -r node_modules
          npm install

      - name: Run perftool
        run: |
          cd spec/main-suite
          npm run integration:npm

  bad_ts-node:
    name: Project with different TS-node version
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Setup packages
        run: pnpm install

      - name: Prepare
        run: |
          cd spec/main-suite
          pnpm run integration:prepare

      - name: Install bad ts-node version
        run: |
          cd spec/main-suite
          pnpm add ts-node@9.1.1

      - name: Run perftool
        run: |
          cd spec/main-suite
          pnpm run integration:unchanged

  bad_typescript:
    name: Project with different typescript version
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Setup packages
        run: pnpm install

      - name: Prepare
        run: |
          cd spec/main-suite
          pnpm run integration:prepare

      - name: Install bad ts-node version
        run: |
          cd spec/main-suite
          pnpm add typescript@4.0.8

      - name: Run perftool
        run: |
          cd spec/main-suite
          pnpm run integration:unchanged
